first try at issue 11
WebAhead10/webahead-library-backend pull request #22
Opened 2021-11-21 11:15 UTC by kassimbashir

Relates #11

2021-11-21 20:16 UTC, Karyum requested changes

2021-11-21 20:16 UTC, Karyum commented on src/middleware/verifyToken.ts
> +        const header = req.headers['authorization'];
```suggestion
        const header = req.headers.authorization;
```

2021-11-21 20:16 UTC, Karyum commented on src/middleware/verifyToken.ts
> +        if(typeof header !== 'undefined'){
```suggestion
        if(header){
```

2021-11-21 20:16 UTC, Karyum commented on src/middleware/verifyToken.ts
> +            const token = header.split(' ')[1];
why is there a space ? does the header look like this ? `Bearer TOKEN22#*@(#@SDSD`

2021-11-21 20:16 UTC, Karyum commented on src/middleware/verifyToken.ts
> +           jwt.verify(token,secret,async (err,data)=>{
Change this to sync, no reason to be async and give it a callback

Example from docs:

```js
  var decoded = jwt.verify(token, 'SECRET');

```

2021-11-21 20:16 UTC, Karyum commented on src/middleware/verifyToken.ts
> +                    const user_id = data.id;
```suggestion
                    const userId = data.id;
```

2021-11-21 20:16 UTC, Karyum commented on src/middleware/verifyToken.ts
> +                    const result = await db.query('SELECT * FROM users WHERE id = $1', [user_id])
```suggestion
                    const result = await db.query('SELECT * FROM users WHERE id = $1', [userId])
```

2021-11-21 20:16 UTC, Karyum commented on src/middleware/verifyToken.ts
> +                    req.user = result.rows;
```suggestion
                    req.user = result.rows[0];
```

2021-11-23 07:51 UTC, kassimbashir commented on src/middleware/verifyToken.ts
> +            const token = header.split(' ')[1];
yes it does

2021-11-23 07:54 UTC, kassimbashir commented on src/middleware/verifyToken.ts
> +           jwt.verify(token,secret,async (err,data)=>{
ok boss

2021-11-23 14:50 UTC, Karyum approved these changes

2021-11-23 14:50 UTC, merged